// Every Bhojpuri keyword lives here. Change a value to rename a keyword —
// the tokenizer, error messages, CLI and playground all read from this table.
// Multi-word keywords are allowed; the words may be separated by any spaces/tabs.
export const KEYWORDS = Object.freeze({
  PROGRAM_START: "ka ho bhaiya",
  PROGRAM_END: "chalat bani bhaiya",
  LET: "maan la",
  PRINT: "bol ho",
  IF: "jadi",
  ELSE_IF: "na ta jadi",
  ELSE: "na ta",
  WHILE: "jab le",
  FOR: "har",
  BREAK: "bas kara",
  CONTINUE: "aage badha",
  FUNCTION: "kaam",
  RETURN: "lauta da",
  TRY: "koshish kara",
  CATCH: "galti pe",
  THROW: "phenk da",
  IMPORT: "le aaw",
  TRUE: "sach",
  FALSE: "jhooth",
  NULL: "khaali",
});

// What each keyword means, for the README, CLI help and playground cheat sheet.
export const KEYWORD_MEANINGS = Object.freeze({
  PROGRAM_START: "start of program",
  PROGRAM_END: "end of program",
  LET: "declare a variable (let)",
  PRINT: "print (console.log)",
  IF: "if",
  ELSE_IF: "else if",
  ELSE: "else",
  WHILE: "while loop",
  FOR: "for loop: har i = 1 se 10 tak { } or har x list me { }",
  BREAK: "break",
  CONTINUE: "continue",
  FUNCTION: "define a function",
  RETURN: "return",
  TRY: "try: koshish kara { } galti pe (g) { }",
  CATCH: "catch: runs when the koshish block fails; g is the error",
  THROW: "throw your own error: phenk da \"...\";",
  IMPORT: "use another file's functions: le aaw \"ganit.bhoj\";",
  TRUE: "true",
  FALSE: "false",
  NULL: "null",
});

// Words that only have a special meaning inside a `har` loop header, e.g.
// `har i = 1 se 10 tak kadam 2 { }` or `har x list me { }`. Everywhere else they are
// ordinary names, so programs can still use them as variables. Each must be one word.
export const LOOP_WORDS = Object.freeze({
  FROM: "se",
  TO: "tak",
  STEP: "kadam",
  IN: "me",
});

// Built-in functions. These are ordinary names, not keywords, so a program may
// shadow them with its own variables.
export const BUILTINS = Object.freeze({
  LENGTH: "lambai",
  PUSH: "daal",
  POP: "nikaal",
  TO_NUMBER: "sankhya",
  TO_STRING: "shabd",
  TYPE: "kism",
  ROUND: "gol",
  FLOOR: "neeche",
  RANDOM: "sanyog",
  UPPER: "bada",
  LOWER: "chhota",
  SPLIT: "tod",
  JOIN: "jod",
  KEYS: "chaabi",
  HAS: "ba",
  REMOVE: "hataw",
  INPUT: "poochh",
  SORT: "chhaant",
  REVERSE: "ulta",
  SLICE: "hissa",
  FIND: "khoj",
  SUM: "kul",
  MAP: "badal",
  FILTER: "chhaan",
  TRIM: "saaf",
  REPLACE: "jagah",
  STARTS_WITH: "shuru_me",
  ENDS_WITH: "ant_me",
  MAX: "sabse_bada",
  MIN: "sabse_chhota",
  CEIL: "upar",
  ABS: "bina_chinh",
});

export const BUILTIN_MEANINGS = Object.freeze({
  LENGTH: "length of a list, letters in a string, or number of keys in a kosh",
  PUSH: "add an item to the end of a list",
  POP: "remove and return the last item of a list",
  TO_NUMBER: "turn text into a number",
  TO_STRING: "turn any value into text",
  TYPE: "the type of a value (sankhya, shabd, list, kosh, ...)",
  ROUND: "round to a whole number, or to some decimal places: gol(2.345, 2) is 2.35",
  FLOOR: "round down to a whole number",
  RANDOM: "random whole number from a to b (inclusive)",
  UPPER: "text in UPPER case",
  LOWER: "text in lower case",
  SPLIT: "split text into a list at each separator",
  JOIN: "join a list into text with a separator",
  KEYS: "list of a kosh's keys, in the order they were added",
  HAS: "sach if a kosh has the key, a list has the item, or a string has the text",
  REMOVE: "remove a key from a kosh and return its value (khaali if missing)",
  INPUT: "ask a question and return the typed answer as text (khaali if none)",
  SORT: "a new list, sorted (all numbers or all strings)",
  REVERSE: "a list or string, reversed",
  SLICE: "part of a list or string: hissa(x, start, end); end is optional",
  FIND: "where an item (or text) first appears, or -1",
  SUM: "the total of a list of numbers",
  MAP: "a new list: a kaam applied to every item, badal(list, kaam(x) { ... })",
  FILTER: "a new list of the items a kaam says sach to, chhaan(list, kaam(x) { ... })",
  TRIM: "text without the spaces at the start and end",
  REPLACE: "text with every purana replaced by naya: jagah(text, purana, naya)",
  STARTS_WITH: "sach if the text starts with the given text",
  ENDS_WITH: "sach if the text ends with the given text",
  MAX: "the largest item of a list (all numbers or all strings)",
  MIN: "the smallest item of a list (all numbers or all strings)",
  CEIL: "round up to a whole number",
  ABS: "the number without its sign: bina_chinh(-5) is 5",
});
